services:
#  postgres:
#    image: postgres:16-alpine
#    container_name: songket-postgres
#    restart: unless-stopped
#    environment:
#      POSTGRES_USER: ${DB_USERNAME:-shagya}
#      POSTGRES_PASSWORD: ${DB_PASS:-shagya22}
#      POSTGRES_DB: ${DB_NAME:-songket}
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-shagya} -d ${DB_NAME:-songket}"]
#      interval: 5s
#      timeout: 3s
#      retries: 10
#      start_period: 10s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: songket-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST:-localhost}
      DB_PORT: ${DB_PORT:-5432}
      DB_SSLMODE: disable
      DB_USERNAME: ${DB_USERNAME:-shagya}
      DB_PASS: ${DB_PASS:-shagya22}
      DB_NAME: ${DB_NAME:-songket}
      PORT: ${PORT:-8080}
      SCRAPE_PANGAN_PYTHON: /opt/songket-venv/bin/python
      SCRAPE_BERITA_PYTHON: /opt/songket-venv/bin/python
      SCRAPE_BERITA_SCRIPT: python/songket-scraping/scrape_berita.py
      #    environment:
      #      POSTGRES_USER: ${DB_USERNAME:-shagya}
      #      POSTGRES_PASSWORD: ${DB_PASS:-shagya22}
      #      POSTGRES_DB: ${DB_NAME:-songket}
   # depends_on:
   #   postgres:
    #    condition: service_healthy
#    ports:
#      - "${PORT:-8080}:${PORT:-8080}"
    network_mode: "host"

  frontend:
    build:
      context: ./songket-fe
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8080}
    container_name: songket-frontend
    restart: unless-stopped
    environment:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8080}
        PORT: ${FRONTEND_PORT:-80}
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT:-3000}:80"

volumes:
  pgdata:
