version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: songket-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: shagya
      POSTGRES_PASSWORD: shagya22
      POSTGRES_DB: songket
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shagya -d songket"]
      interval: 5s
      retries: 5
      start_period: 5s
volumes:
  pgdata:
